
#ifndef VTKUTILITIESPYTHONINITIALIZER_EXPORT_H
#define VTKUTILITIESPYTHONINITIALIZER_EXPORT_H

#ifdef VTKUTILITIESPYTHONINITIALIZER_STATIC_DEFINE
#  define VTKUTILITIESPYTHONINITIALIZER_EXPORT
#  define VTKUTILITIESPYTHONINITIALIZER_NO_EXPORT
#else
#  ifndef VTKUTILITIESPYTHONINITIALIZER_EXPORT
#    ifdef PythonInitializer_EXPORTS
        /* We are building this library */
#      define VTKUTILITIESPYTHONINITIALIZER_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define VTKUTILITIESPYTHONINITIALIZER_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef VTKUTILITIESPYTHONINITIALIZER_NO_EXPORT
#    define VTKUTILITIESPYTHONINITIALIZER_NO_EXPORT 
#  endif
#endif

#ifndef VTKUTILITIESPYTHONINITIALIZER_DEPRECATED
#  define VTKUTILITIESPYTHONINITIALIZER_DEPRECATED __declspec(deprecated)
#endif

#ifndef VTKUTILITIESPYTHONINITIALIZER_DEPRECATED_EXPORT
#  define VTKUTILITIESPYTHONINITIALIZER_DEPRECATED_EXPORT VTKUTILITIESPYTHONINITIALIZER_EXPORT VTKUTILITIESPYTHONINITIALIZER_DEPRECATED
#endif

#ifndef VTKUTILITIESPYTHONINITIALIZER_DEPRECATED_NO_EXPORT
#  define VTKUTILITIESPYTHONINITIALIZER_DEPRECATED_NO_EXPORT VTKUTILITIESPYTHONINITIALIZER_NO_EXPORT VTKUTILITIESPYTHONINITIALIZER_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKUTILITIESPYTHONINITIALIZER_NO_DEPRECATED
#    define VTKUTILITIESPYTHONINITIALIZER_NO_DEPRECATED
#  endif
#endif

/* VTK-HeaderTest-Exclude: vtkUtilitiesPythonInitializerModule.h */

/* Include ABI Namespace */
#include "vtkABINamespace.h"

#endif /* VTKUTILITIESPYTHONINITIALIZER_EXPORT_H */
