#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2204-78-ga9e1d88e"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2204
#define NETGEN_VERSION_TWEAK 78
#define NETGEN_VERSION_HASH "ga9e1d88e"
#endif // NETGEN_VERSION_HPP_INCLUDED
