#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2105-154-gc63a865e"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2105
#define NETGEN_VERSION_TWEAK 154
#define NETGEN_VERSION_HASH "gc63a865e"
#endif // NETGEN_VERSION_HPP_INCLUDED
