
#ifndef VTKPVVTKEXTENSIONSEXTRACTIONPYTHON_EXPORT_H
#define VTKPVVTKEXTENSIONSEXTRACTIONPYTHON_EXPORT_H

#ifdef VTKPVVTKEXTENSIONSEXTRACTIONPYTHON_STATIC_DEFINE
#  define VTKPVVTKEXTENSIONSEXTRACTIONPYTHON_EXPORT
#  define VTKPVVTKEXTENSIONSEXTRACTIONPYTHON_NO_EXPORT
#else
#  ifndef VTKPVVTKEXTENSIONSEXTRACTIONPYTHON_EXPORT
#    ifdef VTKExtensionsExtractionPython_EXPORTS
        /* We are building this library */
#      define VTKPVVTKEXTENSIONSEXTRACTIONPYTHON_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define VTKPVVTKEXTENSIONSEXTRACTIONPYTHON_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef VTKPVVTKEXTENSIONSEXTRACTIONPYTHON_NO_EXPORT
#    define VTKPVVTKEXTENSIONSEXTRACTIONPYTHON_NO_EXPORT 
#  endif
#endif

#ifndef VTKPVVTKEXTENSIONSEXTRACTIONPYTHON_DEPRECATED
#  define VTKPVVTKEXTENSIONSEXTRACTIONPYTHON_DEPRECATED __declspec(deprecated)
#endif

#ifndef VTKPVVTKEXTENSIONSEXTRACTIONPYTHON_DEPRECATED_EXPORT
#  define VTKPVVTKEXTENSIONSEXTRACTIONPYTHON_DEPRECATED_EXPORT VTKPVVTKEXTENSIONSEXTRACTIONPYTHON_EXPORT VTKPVVTKEXTENSIONSEXTRACTIONPYTHON_DEPRECATED
#endif

#ifndef VTKPVVTKEXTENSIONSEXTRACTIONPYTHON_DEPRECATED_NO_EXPORT
#  define VTKPVVTKEXTENSIONSEXTRACTIONPYTHON_DEPRECATED_NO_EXPORT VTKPVVTKEXTENSIONSEXTRACTIONPYTHON_NO_EXPORT VTKPVVTKEXTENSIONSEXTRACTIONPYTHON_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKPVVTKEXTENSIONSEXTRACTIONPYTHON_NO_DEPRECATED
#    define VTKPVVTKEXTENSIONSEXTRACTIONPYTHON_NO_DEPRECATED
#  endif
#endif

/* VTK-HeaderTest-Exclude: vtkPVVTKExtensionsExtractionPythonModule.h */

/* Include ABI Namespace */
#include "vtkABINamespace.h"

#endif /* VTKPVVTKEXTENSIONSEXTRACTIONPYTHON_EXPORT_H */
