
#ifndef VTKPVPYTHONCATALYST_EXPORT_H
#define VTKPVPYTHONCATALYST_EXPORT_H

#ifdef VTKPVPYTHONCATALYST_STATIC_DEFINE
#  define VTKPVPYTHONCATALYST_EXPORT
#  define VTKPVPYTHONCATALYST_NO_EXPORT
#else
#  ifndef VTKPVPYTHONCATALYST_EXPORT
#    ifdef PythonCatalyst_EXPORTS
        /* We are building this library */
#      define VTKPVPYTHONCATALYST_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define VTKPVPYTHONCATALYST_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef VTKPVPYTHONCATALYST_NO_EXPORT
#    define VTKPVPYTHONCATALYST_NO_EXPORT 
#  endif
#endif

#ifndef VTKPVPYTHONCATALYST_DEPRECATED
#  define VTKPVPYTHONCATALYST_DEPRECATED __declspec(deprecated)
#endif

#ifndef VTKPVPYTHONCATALYST_DEPRECATED_EXPORT
#  define VTKPVPYTHONCATALYST_DEPRECATED_EXPORT VTKPVPYTHONCATALYST_EXPORT VTKPVPYTHONCATALYST_DEPRECATED
#endif

#ifndef VTKPVPYTHONCATALYST_DEPRECATED_NO_EXPORT
#  define VTKPVPYTHONCATALYST_DEPRECATED_NO_EXPORT VTKPVPYTHONCATALYST_NO_EXPORT VTKPVPYTHONCATALYST_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKPVPYTHONCATALYST_NO_DEPRECATED
#    define VTKPVPYTHONCATALYST_NO_DEPRECATED
#  endif
#endif

/* VTK-HeaderTest-Exclude: vtkPVPythonCatalystModule.h */

/* Include ABI Namespace */
#include "vtkABINamespace.h"

#endif /* VTKPVPYTHONCATALYST_EXPORT_H */
