
#ifndef VTKREMOTINGAPPLICATIONCOMPONENTS_EXPORT_H
#define VTKREMOTINGAPPLICATIONCOMPONENTS_EXPORT_H

#ifdef VTKREMOTINGAPPLICATIONCOMPONENTS_STATIC_DEFINE
#  define VTKREMOTINGAPPLICATIONCOMPONENTS_EXPORT
#  define VTKREMOTINGAPPLICATIONCOMPONENTS_NO_EXPORT
#else
#  ifndef VTKREMOTINGAPPLICATIONCOMPONENTS_EXPORT
#    ifdef RemotingApplicationComponents_EXPORTS
        /* We are building this library */
#      define VTKREMOTINGAPPLICATIONCOMPONENTS_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define VTKREMOTINGAPPLICATIONCOMPONENTS_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef VTKREMOTINGAPPLICATIONCOMPONENTS_NO_EXPORT
#    define VTKREMOTINGAPPLICATIONCOMPONENTS_NO_EXPORT 
#  endif
#endif

#ifndef VTKREMOTINGAPPLICATIONCOMPONENTS_DEPRECATED
#  define VTKREMOTINGAPPLICATIONCOMPONENTS_DEPRECATED __declspec(deprecated)
#endif

#ifndef VTKREMOTINGAPPLICATIONCOMPONENTS_DEPRECATED_EXPORT
#  define VTKREMOTINGAPPLICATIONCOMPONENTS_DEPRECATED_EXPORT VTKREMOTINGAPPLICATIONCOMPONENTS_EXPORT VTKREMOTINGAPPLICATIONCOMPONENTS_DEPRECATED
#endif

#ifndef VTKREMOTINGAPPLICATIONCOMPONENTS_DEPRECATED_NO_EXPORT
#  define VTKREMOTINGAPPLICATIONCOMPONENTS_DEPRECATED_NO_EXPORT VTKREMOTINGAPPLICATIONCOMPONENTS_NO_EXPORT VTKREMOTINGAPPLICATIONCOMPONENTS_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKREMOTINGAPPLICATIONCOMPONENTS_NO_DEPRECATED
#    define VTKREMOTINGAPPLICATIONCOMPONENTS_NO_DEPRECATED
#  endif
#endif

/* VTK-HeaderTest-Exclude: vtkRemotingApplicationComponentsModule.h */

/* Include ABI Namespace */
#include "vtkABINamespace.h"

#endif /* VTKREMOTINGAPPLICATIONCOMPONENTS_EXPORT_H */
