
#ifndef VTKUTILITIESPYTHONINTERPRETERPATH_EXPORT_H
#define VTKUTILITIESPYTHONINTERPRETERPATH_EXPORT_H

#ifdef VTKUTILITIESPYTHONINTERPRETERPATH_STATIC_DEFINE
#  define VTKUTILITIESPYTHONINTERPRETERPATH_EXPORT
#  define VTKUTILITIESPYTHONINTERPRETERPATH_NO_EXPORT
#else
#  ifndef VTKUTILITIESPYTHONINTERPRETERPATH_EXPORT
#    ifdef PythonInterpreterPath_EXPORTS
        /* We are building this library */
#      define VTKUTILITIESPYTHONINTERPRETERPATH_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define VTKUTILITIESPYTHONINTERPRETERPATH_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef VTKUTILITIESPYTHONINTERPRETERPATH_NO_EXPORT
#    define VTKUTILITIESPYTHONINTERPRETERPATH_NO_EXPORT 
#  endif
#endif

#ifndef VTKUTILITIESPYTHONINTERPRETERPATH_DEPRECATED
#  define VTKUTILITIESPYTHONINTERPRETERPATH_DEPRECATED __declspec(deprecated)
#endif

#ifndef VTKUTILITIESPYTHONINTERPRETERPATH_DEPRECATED_EXPORT
#  define VTKUTILITIESPYTHONINTERPRETERPATH_DEPRECATED_EXPORT VTKUTILITIESPYTHONINTERPRETERPATH_EXPORT VTKUTILITIESPYTHONINTERPRETERPATH_DEPRECATED
#endif

#ifndef VTKUTILITIESPYTHONINTERPRETERPATH_DEPRECATED_NO_EXPORT
#  define VTKUTILITIESPYTHONINTERPRETERPATH_DEPRECATED_NO_EXPORT VTKUTILITIESPYTHONINTERPRETERPATH_NO_EXPORT VTKUTILITIESPYTHONINTERPRETERPATH_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKUTILITIESPYTHONINTERPRETERPATH_NO_DEPRECATED
#    define VTKUTILITIESPYTHONINTERPRETERPATH_NO_DEPRECATED
#  endif
#endif

/* VTK-HeaderTest-Exclude: vtkUtilitiesPythonInterpreterPathModule.h */

/* Include ABI Namespace */
#include "vtkABINamespace.h"

#endif /* VTKUTILITIESPYTHONINTERPRETERPATH_EXPORT_H */
