##============================================================================
##  The contents of this file are covered by the Viskores license. See
##  LICENSE.txt for details.
##
##  By contributing to this file, all contributors agree to the Developer
##  Certificate of Origin Version 1.1 (DCO 1.1) as stated in DCO.txt.
##============================================================================

##============================================================================
##  Copyright (c) Kitware, Inc.
##  All rights reserved.
##  See LICENSE.txt for details.
##
##  This software is distributed WITHOUT ANY WARRANTY; without even
##  the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
##  PURPOSE.  See the above copyright notice for more information.
##============================================================================

# This file is automatically generated by CMake, do not edit.
Viskores_VERSION = 1.0
Viskores_DIR = D:/source/third-party-auto/VTK/vtk-Release

Viskores_BUILD_SHARED_LIBS = ON
Viskores_ENABLE_CUDA = OFF
Viskores_ENABLE_KOKKOS = OFF
Viskores_ENABLE_OPENMP = OFF
Viskores_ENABLE_TBB = OFF
Viskores_ENABLE_LOGGING = ON
Viskores_ENABLE_RENDERING = OFF
Viskores_ENABLE_GL_CONTEXT = 
Viskores_ENABLE_OSMESA_CONTEXT = 
Viskores_ENABLE_EGL_CONTEXT = 
Viskores_ENABLE_MPI = OFF

Viskores_INCLUDE_DIR = $(Viskores_DIR)/include/viskores-1.0
Viskores_INCLUDE_FLAGS = -I$(Viskores_INCLUDE_DIR) -I$(Viskores_INCLUDE_DIR)/viskores/thirdparty/diy/viskoresdiy/include/ -I$(Viskores_INCLUDE_DIR)/viskores/thirdparty/lcl/viskoreslcl/

Viskores_LIB_FLAGS = -L $(Viskores_DIR)/lib \
    -lviskores_source-9.5 \
    -lviskores_io-9.5 \
    -lviskores_filter_zfp-9.5 \
    -lviskores_filter_uncertainty-9.5 \
    -lviskores_filter_resampling-9.5 \
    -lviskores_filter_image_processing-9.5 \
    -lviskores_filter_flow-9.5 \
    -lviskores_filter_field_transform-9.5 \
    -lviskores_filter_field_conversion-9.5 \
    -lviskores_filter_entity_extraction-9.5 \
    -lviskores_filter_density_estimate-9.5 \
    -lviskores_filter_geometry_refinement-9.5 \
    -lviskores_filter_contour-9.5 \
    -lviskores_filter_multi_block-9.5 \
    -lviskores_filter_mesh_info-9.5 \
    -lviskores_filter_vector_analysis-9.5 \
    -lviskores_filter_connected_components-9.5 \
    -lviskores_filter_clean_grid-9.5 \
    -lviskores_filter_core-9.5 \
    -lviskores_worklet-9.5 \
    -lviskores_cont_testing-9.5 \
    -lviskores_cont-9.5 \
    -lviskoresdiympi_nompi
