#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2405-152-gc27650af"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2405
#define NETGEN_VERSION_TWEAK 152
#define NETGEN_VERSION_HASH "gc27650af"
#endif // NETGEN_VERSION_HPP_INCLUDED
