#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2505-47-g9a2c20ea"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2505
#define NETGEN_VERSION_TWEAK 47
#define NETGEN_VERSION_HASH "g9a2c20ea"
#endif // NETGEN_VERSION_HPP_INCLUDED
